### ISSUE TITLE
[Quest line: Productive Bees shown twice]: 

### ISSUE THREAD

**Issue by Rapchor** [AllTheMods/All-the-mods-9-Sky#645] opened 2024-08-03 10:09 UTC
### Possible Fixes

Yes

### Modpack Version

1.1.0

### What happened?

Updated my AlltheMods9 to the sky version from 1.0.8 to 1.0.9 and then there were 2 Questlines of Productive Bees ...

**Comment by ReikoAldrakar** [comment] 2024-08-03 10:58
Dupe of #594 and #605

**Comment by rsandbach** [comment] 2024-08-31 02:26
Seems like this may be caused by having multiple chapter files for productive bees.

productive_bees.snbt and atm9chapters16title.snbt have the quests productive bees, but are different enough to not immediately understand which is the one that should be kept. 

https://github.com/AllTheMods/All-the-mods-9-Sky/commit/04f37b191d3ddbc8aa3273b20051d02555464eca#diff-52477635e20be2ad315b568341ef47a00328e3ca13de40a2eaec6f694103ca3c

**Closed as completed** 2024-09-29 11:42 UTC
Labels: Bug, Duplicate
