### ISSUE TITLE
[Bug]: Can't craft refined obsidian dust

### ISSUE THREAD

**Issue by richhuff** [AllTheMods/All-the-mods-9-Sky#466] opened 2024-06-30 17:31 UTC
### Possible Fixes

Yes

### Modpack Version

1.0.6

### What happened?

Can't craft enriched obsidian in diamond infuser with AE2 crafting.  Pattern specifies Mekanism obsidian dust. AE2 crafter is trying to use Occultism obsidian dust (which doesn't have a recipe).

### latest.log

https://gist.github.com/richhuff/9b5fa8f0bfcefd9285cb372eab7dced8

**Comment by TheLastPaladin** [comment] 2024-07-01 15:19
I've tested the issue that you described, however I cannot reproduce it. Please make sure that you are running 1.0.6 and your AE2 autocrafting is correctly setup. Please consider that the Infusing Factory does NOT accept item input and special (in your case diamond) input through the same side.

**Comment by richhuff** [comment] 2024-07-02 17:56
This can be closed. My obsidian dust crafting pattern was incorrect.

**Comment by TheLastPaladin** [comment] 2024-07-02 22:58
Then close it. I'm not the author of this post, you are ;)

**Closed** 2024-07-03 01:08 UTC
Labels: Bug
