### ISSUE TITLE
[Bug]: No JEI recipe for Gaia Spirit Crux

### ISSUE THREAD

**Issue by MoonDance911** [AllTheMods/All-the-mods-9-Sky#651] opened 2024-08-05 13:06 UTC
### Possible Fixes

Yes

### Modpack Version

1.1.0

### What happened?

[Bug]: No JEI recipe for Gaia Spirit Crux

**Comment by ReikoAldrakar** [comment] 2024-08-05 20:55
Dupe of #199
And looking at PR #619 it is intentional as they added the Gaia Crux to the JEI blacklist
You can farm gaia essence with the Phytogenic Insolator tho, as that one doesn't require the Crux^^

**Closed as not planned** 2024-09-28 07:36 UTC
Labels: Duplicate, Suggestion
