### ISSUE TITLE
[Bug]: LaserIO open filter and sort inventory deletes half my inventory

### ISSUE THREAD

**Issue by mahall1988** [AllTheMods/All-the-mods-9-Sky#521] opened 2024-07-07 16:06 UTC
### Possible Fixes

Yes

### Modpack Version

1.0.7

### What happened?

when i opened a laserio filter on its own, not inside a node, and sort my inventory it tries to put my inventory into the filter and they only appear as ghost items in the card but disappear from my inventory.

**Comment by anmcn** [comment] 2024-07-11 01:39
See also upstream bug report: https://github.com/Direwolf20-MC/LaserIO/issues/265

**Comment by mtpb** [comment] 2024-08-21 12:41
Duplicate of #98 
Still occurs in version 1.1.1
<details>
<summary>Steps to reproduce</summary>

1. Have some items in your inventory
2. Open an Item Card GUI in Laser Node from LaserIO
3. Place filter in the Item Card GUI
4. Middle-click on any slot in the filter GUI
5. The filter alongside a portion of your inventory will get deleted

</details>

**Comment by pmteixeira07** [comment] 2024-10-31 03:57
The problem is with Inventory Tweaks Renewed. Sorting the inventory in modded inventories using that mod deletes your inventory!

**Closed as completed** 2024-11-01 09:01 UTC
Labels: Bug, Duplicate
