### ISSUE TITLE
[Crash]: JEI/Alchemistry LiquifierScreen

### ISSUE THREAD

**Issue by Jared87** [AllTheMods/All-the-mods-9-Sky#650] opened 2024-08-05 09:02 UTC
### Possible Fixes

Yes

### Modpack Version

1.1.0

### What happened?

Client is crashing every time when i  try to open the JEI recipesof the Alchemistry Liquifier.

### Crash Log

https://gist.github.com/Jared87/5d3bf50442743079e58b91417050a00a

**Comment by TheBedrockMaster** [comment] 2024-08-05 11:39
Duplicate of https://github.com/AllTheMods/All-the-mods-9-Sky/issues/641

**Closed as completed** 2024-11-22 00:04 UTC
Labels: Duplicate, Crash
