### ISSUE TITLE
[Bug]: Not able to place Iron Ingot in Energy Condenser

### ISSUE THREAD

**Issue by ThatGuy6937** [AllTheMods/All-the-mods-9-Sky#547] opened 2024-07-12 18:50 UTC
### Possible Fixes

Yes

### Modpack Version

1.0.7

### What happened?

Iron ingots (and almost all other valuable resource) seem to not have an EMC value and therefore are unable to be placed into the target slot of the energy condenser. I'm not sure if this is intentional or not but it seems strange. Any advice would be appreciated!

**Comment by Koupius** [comment] 2024-07-12 19:24
Not a bug. Most items have had their EMC values taken away, leaving mostly decorative items with EMC. If you would like to restore EMC values to most items you can delete the "mappings" file in your projectE config folder.

**Comment by TheBedrockMaster** [comment] 2024-07-13 01:20
This can be closed as not planned.

**Closed as not planned** 2024-07-13 23:04 UTC
Labels: Won't Fix
