### ISSUE TITLE
Apotheosis Gear missing items in quests due to mod update

### ISSUE THREAD

**Issue by asoshinsky** [AllTheMods/All-the-mods-9-Sky#623] opened 2024-07-27 21:03 UTC
### Modpack Version

1.0.8a

### Describe the issue

Because the apotheosis mod got updated in some of the older modpack versions they removed vials. Now they appear as missing items and therefore it's impossible to complete the chapter
![Quest Apotheosis](https://github.com/user-attachments/assets/e786620d-6761-407b-85bb-bdc4a08846dc)

**Comment by ReikoAldrakar** [comment] 2024-07-28 19:58
This is fixed in the newest version of the modpack -> 1.0.9

Duplicate of #590

**Closed as completed** 2024-07-28 20:27 UTC
Labels: Quest Bug
